In [1]:
import pandas as pd
import geopandas as gpd
import cartopy.crs as ccrs
import zipfile
import os
import pathlib
import hvplot.pandas
%pip install geoviews
import geoviews as gv
%pip install jupyter_bokeh

Requirement already satisfied: geoviews in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (1.15.1)
Requirement already satisfied: bokeh>=3.8.0 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from geoviews) (3.8.1)
Requirement already satisfied: cartopy>=0.18.0 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from geoviews) (0.25.0)
Requirement already satisfied: holoviews>=1.16.0 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from geoviews) (1.22.1)
Requirement already satisfied: numpy in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from geoviews) (2.3.5)
Requirement already satisfied: packaging in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from geoviews) (25.0)
Requirement already satisfied: panel>=1.0.0 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from geoviews) (1.8.5)
Requirement already satisfied: param<3.0,>=1.9.3 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from geoviews) (2.3.1)
Requirement already satisfied: pyproj in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from geoviews) (3.7.2)
Requirement already satisfied: shapely>=1.8.0 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from geoviews) (2.1.2)
Requirement already satisfied: xyzservices in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from geoviews) (2025.11.0)
Requirement already satisfied: Jinja2>=2.9 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from bokeh>=3.8.0->geoviews) (3.1.6)
Requirement already satisfied: contourpy>=1.2 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from bokeh>=3.8.0->geoviews) (1.3.3)
Requirement already satisfied: narwhals>=1.13 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from bokeh>=3.8.0->geoviews) (2.15.0)
Requirement already satisfied: pandas>=1.2 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from bokeh>=3.8.0->geoviews) (2.2.3)
Requirement already satisfied: pillow>=7.1.0 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from bokeh>=3.8.0->geoviews) (12.1.0)
Requirement already satisfied: PyYAML>=3.10 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from bokeh>=3.8.0->geoviews) (6.0.3)
Requirement already satisfied: tornado>=6.2 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from bokeh>=3.8.0->geoviews) (6.5.4)
Requirement already satisfied: matplotlib>=3.6 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from cartopy>=0.18.0->geoviews) (3.10.8)
Requirement already satisfied: pyshp>=2.3 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from cartopy>=0.18.0->geoviews) (2.3.1)
Requirement already satisfied: colorcet in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from holoviews>=1.16.0->geoviews) (3.1.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from holoviews>=1.16.0->geoviews) (2.9.0.post0)
Requirement already satisfied: pyviz-comms>=2.1 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from holoviews>=1.16.0->geoviews) (3.0.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from Jinja2>=2.9->bokeh>=3.8.0->geoviews) (3.0.3)
Requirement already satisfied: cycler>=0.10 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from matplotlib>=3.6->cartopy>=0.18.0->geoviews) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from matplotlib>=3.6->cartopy>=0.18.0->geoviews) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from matplotlib>=3.6->cartopy>=0.18.0->geoviews) (1.4.9)
Requirement already satisfied: pyparsing>=3 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from matplotlib>=3.6->cartopy>=0.18.0->geoviews) (3.3.1)
Requirement already satisfied: pytz>=2020.1 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from pandas>=1.2->bokeh>=3.8.0->geoviews) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from pandas>=1.2->bokeh>=3.8.0->geoviews) (2025.3)
Requirement already satisfied: bleach in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from panel>=1.0.0->geoviews) (6.3.0)
Requirement already satisfied: linkify-it-py in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from panel>=1.0.0->geoviews) (2.0.3)
Requirement already satisfied: markdown in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from panel>=1.0.0->geoviews) (3.10)
Requirement already satisfied: markdown-it-py in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from panel>=1.0.0->geoviews) (4.0.0)
Requirement already satisfied: mdit-py-plugins in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from panel>=1.0.0->geoviews) (0.5.0)
Requirement already satisfied: requests in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from panel>=1.0.0->geoviews) (2.32.5)
Requirement already satisfied: tqdm in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from panel>=1.0.0->geoviews) (4.67.1)
Requirement already satisfied: typing-extensions in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from panel>=1.0.0->geoviews) (4.15.0)
Requirement already satisfied: certifi in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from pyproj->geoviews) (2026.1.4)
Requirement already satisfied: six>=1.5 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from python-dateutil>=2.8.2->holoviews>=1.16.0->geoviews) (1.17.0)
Requirement already satisfied: webencodings in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from bleach->panel>=1.0.0->geoviews) (0.5.1)
Requirement already satisfied: uc-micro-py in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from linkify-it-py->panel>=1.0.0->geoviews) (1.0.3)
Requirement already satisfied: mdurl~=0.1 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from markdown-it-py->panel>=1.0.0->geoviews) (0.1.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from requests->panel>=1.0.0->geoviews) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from requests->panel>=1.0.0->geoviews) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from requests->panel>=1.0.0->geoviews) (2.6.3)
Requirement already satisfied: colorama in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from tqdm->panel>=1.0.0->geoviews) (0.4.6)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: jupyter_bokeh in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (4.0.5)
Requirement already satisfied: bokeh==3.* in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from jupyter_bokeh) (3.8.1)
Requirement already satisfied: ipywidgets==8.* in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from jupyter_bokeh) (8.1.8)
Requirement already satisfied: Jinja2>=2.9 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from bokeh==3.*->jupyter_bokeh) (3.1.6)
Requirement already satisfied: contourpy>=1.2 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from bokeh==3.*->jupyter_bokeh) (1.3.3)
Requirement already satisfied: narwhals>=1.13 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from bokeh==3.*->jupyter_bokeh) (2.15.0)
Requirement already satisfied: numpy>=1.16 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from bokeh==3.*->jupyter_bokeh) (2.3.5)
Requirement already satisfied: packaging>=16.8 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from bokeh==3.*->jupyter_bokeh) (25.0)
Requirement already satisfied: pandas>=1.2 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from bokeh==3.*->jupyter_bokeh) (2.2.3)
Requirement already satisfied: pillow>=7.1.0 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from bokeh==3.*->jupyter_bokeh) (12.1.0)
Requirement already satisfied: PyYAML>=3.10 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from bokeh==3.*->jupyter_bokeh) (6.0.3)
Requirement already satisfied: tornado>=6.2 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from bokeh==3.*->jupyter_bokeh) (6.5.4)
Requirement already satisfied: xyzservices>=2021.09.1 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from bokeh==3.*->jupyter_bokeh) (2025.11.0)
Requirement already satisfied: comm>=0.1.3 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from ipywidgets==8.*->jupyter_bokeh) (0.2.3)
Requirement already satisfied: ipython>=6.1.0 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from ipywidgets==8.*->jupyter_bokeh) (9.9.0)
Requirement already satisfied: traitlets>=4.3.1 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from ipywidgets==8.*->jupyter_bokeh) (5.14.3)
Requirement already satisfied: widgetsnbextension~=4.0.14 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from ipywidgets==8.*->jupyter_bokeh) (4.0.15)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from ipywidgets==8.*->jupyter_bokeh) (3.0.16)
Requirement already satisfied: colorama>=0.4.4 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from ipython>=6.1.0->ipywidgets==8.*->jupyter_bokeh) (0.4.6)
Requirement already satisfied: decorator>=4.3.2 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from ipython>=6.1.0->ipywidgets==8.*->jupyter_bokeh) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from ipython>=6.1.0->ipywidgets==8.*->jupyter_bokeh) (1.1.1)
Requirement already satisfied: jedi>=0.18.1 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from ipython>=6.1.0->ipywidgets==8.*->jupyter_bokeh) (0.19.2)
Requirement already satisfied: matplotlib-inline>=0.1.5 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from ipython>=6.1.0->ipywidgets==8.*->jupyter_bokeh) (0.2.1)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from ipython>=6.1.0->ipywidgets==8.*->jupyter_bokeh) (3.0.52)
Requirement already satisfied: pygments>=2.11.0 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from ipython>=6.1.0->ipywidgets==8.*->jupyter_bokeh) (2.19.2)
Requirement already satisfied: stack_data>=0.6.0 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from ipython>=6.1.0->ipywidgets==8.*->jupyter_bokeh) (0.6.3)
Requirement already satisfied: typing_extensions>=4.6 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from ipython>=6.1.0->ipywidgets==8.*->jupyter_bokeh) (4.15.0)
Requirement already satisfied: wcwidth in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets==8.*->jupyter_bokeh) (0.2.14)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from jedi>=0.18.1->ipython>=6.1.0->ipywidgets==8.*->jupyter_bokeh) (0.8.5)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from Jinja2>=2.9->bokeh==3.*->jupyter_bokeh) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from pandas>=1.2->bokeh==3.*->jupyter_bokeh) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from pandas>=1.2->bokeh==3.*->jupyter_bokeh) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from pandas>=1.2->bokeh==3.*->jupyter_bokeh) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.2->bokeh==3.*->jupyter_bokeh) (1.17.0)
Requirement already satisfied: executing>=1.2.0 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets==8.*->jupyter_bokeh) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets==8.*->jupyter_bokeh) (3.0.1)
Requirement already satisfied: pure_eval in c:\users\moenc\miniconda3\envs\atoc-2025-lite\lib\site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets==8.*->jupyter_bokeh) (0.2.3)
Note: you may need to restart the kernel to use updated packages.

In [2]:
# load feederwatch data
fdw_df = pd.read_csv("clean_feederwatch.csv")
fdw_df

FileNotFoundError: [Errno 2] No such file or directory: 'clean_feederwatch.csv'

In [ ]:
fdw_gdf = (
    gpd.GeoDataFrame(
        fdw_df, 
        geometry=gpd.points_from_xy(
            fdw_df.LONGITUDE, 
            fdw_df.LATITUDE), 
        crs="EPSG:4326")
    # Select the desired columns
    [['DATE', 'geometry', 'SPECIES_CODE']]
)
fdw_gdf

            DATE                    geometry SPECIES_CODE
0     2024-03-30  POINT (-106.02005 33.0707)       bkchum
1     2024-04-06  POINT (-106.02005 33.0707)       bkchum
2     2024-04-27  POINT (-106.02005 33.0707)       bkchum
3     2023-03-25  POINT (-106.02005 33.0707)       brthum
4     2023-04-22  POINT (-106.02005 33.0707)       bkchum
...          ...                         ...          ...
1361  2022-04-20  POINT (-106.66945 35.1279)       bkchum
1362  2022-04-27  POINT (-106.66945 35.1279)       bkchum
1363  2021-04-15  POINT (-106.66945 35.1279)       bkchum
1364  2021-04-22  POINT (-106.66945 35.1279)       bkchum
1365  2021-04-29  POINT (-106.66945 35.1279)       bkchum

[1366 rows x 3 columns]

In [ ]:
# Create data directory in the home folder
data_dir = os.path.join(
    # Home directory
    pathlib.Path.home(),
    # Earth analytics data directory
    'atoc4815_NECTAR-3',
    'data'
)
data_dir
os.makedirs(data_dir, exist_ok=True)

In [ ]:
nm_download = gpd.read_file("https://www2.census.gov/geo/tiger/GENZ2018/shp/cb_2018_us_county_500k.zip")
nm_download

,STATEFP,COUNTYFP,COUNTYNS,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER,geometry
0,21,007,00516850,0500000US21007,21007,Ballard,06,639387454,69473325,"POLYGON ((-89.18137 37.0463, -89.17938 37.0530..."
1,21,017,00516855,0500000US21017,21017,Bourbon,06,750439351,4829777,"POLYGON ((-84.44266 38.28324, -84.44114 38.283..."
2,21,031,00516862,0500000US21031,21031,Butler,06,1103571974,13943044,"POLYGON ((-86.94486 37.07341, -86.94346 37.074..."
3,21,065,00516879,0500000US21065,21065,Estill,06,655509930,6516335,"POLYGON ((-84.12662 37.6454, -84.12483 37.6461..."
4,21,069,00516881,0500000US21069,21069,Fleming,06,902727151,7182793,"POLYGON ((-83.98428 38.44549, -83.98246 38.450..."
...,...,...,...,...,...,...,...,...,...,...
3228,31,073,00835858,0500000US31073,31073,Gosper,06,1186616237,11831826,"POLYGON ((-100.0951 40.43866, -100.08937 40.43..."
3229,39,075,01074050,0500000US39075,39075,Holmes,06,1094405866,3695230,"POLYGON ((-82.22066 40.66758, -82.19327 40.667..."
3230,48,171,01383871,0500000US48171,48171,Gillespie,06,2740719114,9012764,"POLYGON ((-99.304 30.49983, -99.28234 30.49967..."
3231,55,079,01581100,0500000US55079,55079,Milwaukee,06,625440563,2455383635,"POLYGON ((-88.06959 42.86726, -88.06959 42.872..."
3232,26,139,01623012,0500000US26139,26139,Ottawa,06,1459502408,2765830983,"POLYGON ((-86.26432 43.1183, -86.25103 43.1182..."

In [ ]:
nm_counties = nm_download[nm_download['STATEFP'] == '35']
nm_counties

,STATEFP,COUNTYFP,COUNTYNS,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER,geometry
158,35,007,00929117,0500000US35007,35007,Colfax,06,9733110158,26299632,"POLYGON ((-105.3777 36.5523, -105.3753 36.5562..."
159,35,011,00933054,0500000US35011,35011,De Baca,06,6016819484,29089486,"POLYGON ((-104.89241 34.25992, -104.89174 34.3..."
160,35,051,01702370,0500000US35051,35051,Sierra,06,10829248375,147676270,"POLYGON ((-108.0006 33.47801, -107.96778 33.47..."
546,35,015,00936829,0500000US35015,35015,Eddy,06,10816898665,56282426,"POLYGON ((-104.85152 32.52054, -104.84217 32.5..."
547,35,039,01702368,0500000US35039,35039,Rio Arriba,06,15179587763,91468728,"POLYGON ((-107.62554 36.56587, -107.62523 36.5..."
548,35,045,00936844,0500000US35045,35045,San Juan,06,14289489115,54969313,"POLYGON ((-109.04602 36.25059, -109.046 36.257..."
549,35,055,00933056,0500000US35055,35055,Taos,06,5704119381,3383128,"POLYGON ((-106.05591 36.2995, -106.05594 36.30..."
891,35,019,00929111,0500000US35019,35019,Guadalupe,06,7847072131,2887948,"POLYGON ((-105.31271 34.35405, -105.31301 34.3..."
915,35,033,01702367,0500000US35033,35033,Mora,06,4988962798,6093304,"POLYGON ((-105.71924 35.91684, -105.71769 35.9..."
987,35,017,00915980,0500000US35017,35017,Grant,06,10259428091,15345466,"POLYGON ((-109.04745 33.06943, -109.0469 33.09..."
1763,35,003,00929108,0500000US35003,35003,Catron,06,17933557078,14197373,"POLYGON ((-109.04747 33.25006, -109.04683 33.3..."
1764,35,021,00933055,0500000US35021,35021,Harding,06,5504963126,1162620,"POLYGON ((-104.43904 36.19482, -104.43748 36.1..."
1765,35,037,00929110,0500000US35037,35037,Quay,06,7443334354,18728804,"POLYGON ((-104.12922 34.87093, -104.12902 34.9..."
1816,35,047,00929114,0500000US35047,35047,San Miguel,06,12228666255,51380263,"POLYGON ((-105.7219 35.82283, -105.72179 35.82..."
1817,35,057,00929112,0500000US35057,35057,Torrance,06,8664074443,2303485,"POLYGON ((-106.47118 34.60842, -106.46487 34.6..."
1828,35,061,00933052,0500000US35061,35061,Valencia,06,2762854208,2760092,"POLYGON ((-107.20334 34.78303, -107.20331 34.7..."
2252,35,001,01702363,0500000US35001,35001,Bernalillo,06,3007639331,15855131,"POLYGON ((-107.19676 35.21946, -107.17087 35.2..."
2284,35,006,00933051,0500000US35006,35006,Cibola,06,11758505178,5554603,"POLYGON ((-109.04611 34.69649, -109.04609 34.7..."
2285,35,009,00933053,0500000US35009,35009,Curry,06,3640098081,8190595,"POLYGON ((-103.73976 34.39014, -103.73952 34.5..."
2298,35,013,00929109,0500000US35013,35013,Doña Ana,06,9863129095,17626170,"POLYGON ((-107.29963 32.60537, -107.29947 32.7..."
2357,35,028,01702366,0500000US35028,35028,Los Alamos,06,282827023,224479,"POLYGON ((-106.41855 35.82074, -106.41733 35.8..."
2392,35,027,00929116,0500000US35027,35027,Lincoln,06,12512530061,554839,"POLYGON ((-106.37366 33.6605, -106.26826 33.66..."
2393,35,053,01702371,0500000US35053,35053,Socorro,06,17214061663,4843011,"POLYGON ((-107.72644 34.50447, -107.72532 34.5..."
2457,35,005,01702364,0500000US35005,35005,Chaves,06,15713867248,20519782,"POLYGON ((-105.35344 32.60474, -105.35198 32.6..."
2570,35,041,01702369,0500000US35041,35041,Roosevelt,06,6335242830,18679735,"POLYGON ((-103.94902 34.39014, -103.94897 34.5..."
2631,35,023,00929106,0500000US35023,35023,Hidalgo,06,8905639714,23582051,"POLYGON ((-109.05017 31.48, -109.04984 31.4995..."
2680,35,025,01702365,0500000US35025,35025,Lea,06,11373850144,8360723,"POLYGON ((-103.81451 32.96511, -103.77891 32.9..."
2772,35,059,00929115,0500000US35059,35059,Union,06,9906866299,15466855,"POLYGON ((-104.00934 36.69766, -104.00745 36.6..."
2774,35,031,00929107,0500000US35031,35031,McKinley,06,14117193197,13684636,"POLYGON ((-109.0468 35.36361, -109.04677 35.37..."
2826,35,049,00933322,0500000US35049,35049,Santa Fe,06,4947127762,3376512,"POLYGON ((-106.2505 35.75582, -106.24753 35.75..."
2871,35,035,00929104,0500000US35035,35035,Otero,06,17126456771,36943378,"POLYGON ((-106.3774 32.16902, -106.37691 32.37..."
2966,35,043,00929113,0500000US35043,35043,Sandoval,06,9609141803,10852025,"MULTIPOLYGON (((-106.27698 35.85555, -106.2483..."
3073,35,029,00933057,0500000US35029,35029,Luna,06,7679944776,433660,"POLYGON ((-108.22981 32.20716, -108.22934 32.5..."

In [ ]:
nm_counties.to_crs(26913) #use EPSG 26913 (UTM 13N - NAD83)
counties_plot = nm_counties.hvplot(geo=True, color='white', line_color='black', line_width=1, tiles='CartoLight', frame_width=500)
counties_plot

:Overlay
   .WMTS.I     :WMTS   [Longitude,Latitude]
   .Polygons.I :Polygons   [Longitude,Latitude]

In [ ]:
# This was my attempt to mesh the hummingbird arrival data with the boundaries map, and create an interactive plot showing when different species arrived on the map at which times. It looks to be out of scope for me at the moment to create a more complicated plot, so I'm leaving things here with the boundary map. Hope that helps!


# fdw_gdf = fdw_gdf.to_crs(26913).dropna()
# fdw_gdf['DATE'] = pd.to_datetime(fdw_gdf['DATE'])

# points_plot = fdw_gdf.hvplot.points(
#     'geometry',
#     groupby = 'DATE',
#     widget_location = 'bottom',
#     geo=True,
#     # color='SPECIES_CODE'
# )

# points_plot

TypeError: object of type 'Point' has no len()

Column
    [0] HoloViews(DynamicMap, widget_location='bottom')
    [1] WidgetBox(align=('center', 'end'))
        [0] DiscreteSlider(name='DATE', options={'2021-02-01 00:00:00': np...}, value=np.datetime64('2021-02-01T...)